name: Release EasyRPA Openframework Parent

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
jobs:  
  release:    
    runs-on: ubuntu-latest

#TODO checkout only libraries folder
#TODO run mvn for specific pom.xml. Each flow for each pom.xml
    steps:
      - name: Checkout project
      - uses: actions/checkout@v3          
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8                    
          server-id: github   
          cache: 'maven'
          
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven Release
        run: mvn release:prepare -B -f 'libraries/pox.xml' -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
